// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package meta

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadFileRequest struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadFileRequest) Reset()         { *m = ReadFileRequest{} }
func (m *ReadFileRequest) String() string { return proto.CompactTextString(m) }
func (*ReadFileRequest) ProtoMessage()    {}
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ReadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadFileRequest.Unmarshal(m, b)
}
func (m *ReadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadFileRequest.Marshal(b, m, deterministic)
}
func (m *ReadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadFileRequest.Merge(m, src)
}
func (m *ReadFileRequest) XXX_Size() int {
	return xxx_messageInfo_ReadFileRequest.Size(m)
}
func (m *ReadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadFileRequest proto.InternalMessageInfo

func (m *ReadFileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type ReadFileResponse struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	HashList             []string `protobuf:"bytes,2,rep,name=hashList,proto3" json:"hashList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadFileResponse) Reset()         { *m = ReadFileResponse{} }
func (m *ReadFileResponse) String() string { return proto.CompactTextString(m) }
func (*ReadFileResponse) ProtoMessage()    {}
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ReadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadFileResponse.Unmarshal(m, b)
}
func (m *ReadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadFileResponse.Marshal(b, m, deterministic)
}
func (m *ReadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadFileResponse.Merge(m, src)
}
func (m *ReadFileResponse) XXX_Size() int {
	return xxx_messageInfo_ReadFileResponse.Size(m)
}
func (m *ReadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadFileResponse proto.InternalMessageInfo

func (m *ReadFileResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ReadFileResponse) GetHashList() []string {
	if m != nil {
		return m.HashList
	}
	return nil
}

type ModifyFileRequest struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	HashList             []string `protobuf:"bytes,3,rep,name=hashList,proto3" json:"hashList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyFileRequest) Reset()         { *m = ModifyFileRequest{} }
func (m *ModifyFileRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyFileRequest) ProtoMessage()    {}
func (*ModifyFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ModifyFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyFileRequest.Unmarshal(m, b)
}
func (m *ModifyFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyFileRequest.Marshal(b, m, deterministic)
}
func (m *ModifyFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyFileRequest.Merge(m, src)
}
func (m *ModifyFileRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyFileRequest.Size(m)
}
func (m *ModifyFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyFileRequest proto.InternalMessageInfo

func (m *ModifyFileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ModifyFileRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ModifyFileRequest) GetHashList() []string {
	if m != nil {
		return m.HashList
	}
	return nil
}

type ModifyFileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MissingHashList      []string `protobuf:"bytes,2,rep,name=missingHashList,proto3" json:"missingHashList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyFileResponse) Reset()         { *m = ModifyFileResponse{} }
func (m *ModifyFileResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyFileResponse) ProtoMessage()    {}
func (*ModifyFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ModifyFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyFileResponse.Unmarshal(m, b)
}
func (m *ModifyFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyFileResponse.Marshal(b, m, deterministic)
}
func (m *ModifyFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyFileResponse.Merge(m, src)
}
func (m *ModifyFileResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyFileResponse.Size(m)
}
func (m *ModifyFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyFileResponse proto.InternalMessageInfo

func (m *ModifyFileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ModifyFileResponse) GetMissingHashList() []string {
	if m != nil {
		return m.MissingHashList
	}
	return nil
}

type DeleteFileRequest struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(m, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *DeleteFileRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type DeleteFileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(m, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetVersionRequest struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVersionRequest) Reset()         { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()    {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *GetVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionRequest.Unmarshal(m, b)
}
func (m *GetVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionRequest.Marshal(b, m, deterministic)
}
func (m *GetVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionRequest.Merge(m, src)
}
func (m *GetVersionRequest) XXX_Size() int {
	return xxx_messageInfo_GetVersionRequest.Size(m)
}
func (m *GetVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionRequest proto.InternalMessageInfo

func (m *GetVersionRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type GetVersionResponse struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVersionResponse) Reset()         { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()    {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *GetVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionResponse.Unmarshal(m, b)
}
func (m *GetVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionResponse.Marshal(b, m, deterministic)
}
func (m *GetVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionResponse.Merge(m, src)
}
func (m *GetVersionResponse) XXX_Size() int {
	return xxx_messageInfo_GetVersionResponse.Size(m)
}
func (m *GetVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionResponse proto.InternalMessageInfo

func (m *GetVersionResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*ReadFileRequest)(nil), "meta.ReadFileRequest")
	proto.RegisterType((*ReadFileResponse)(nil), "meta.ReadFileResponse")
	proto.RegisterType((*ModifyFileRequest)(nil), "meta.ModifyFileRequest")
	proto.RegisterType((*ModifyFileResponse)(nil), "meta.ModifyFileResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "meta.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "meta.DeleteFileResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "meta.GetVersionRequest")
	proto.RegisterType((*GetVersionResponse)(nil), "meta.GetVersionResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x69, 0x5a, 0x34, 0x0e, 0x94, 0x9a, 0x05, 0x35, 0xe4, 0x54, 0xf6, 0xd4, 0x8b, 0x11,
	0xf4, 0xe4, 0xa9, 0x17, 0xd1, 0x0a, 0xf6, 0x12, 0x41, 0xbc, 0xae, 0xc9, 0xd4, 0x2e, 0x24, 0xd9,
	0x9a, 0xd9, 0x16, 0xfc, 0x11, 0xfe, 0x67, 0x49, 0xea, 0xba, 0x31, 0xab, 0xb4, 0xe0, 0x71, 0x36,
	0xb3, 0xdf, 0x9b, 0x7d, 0x6f, 0x02, 0x43, 0xc2, 0x6a, 0x23, 0x53, 0x8c, 0x57, 0x95, 0xd2, 0x8a,
	0x0d, 0x0a, 0xd4, 0x82, 0x9f, 0xc3, 0x28, 0x41, 0x91, 0xdd, 0xca, 0x1c, 0x13, 0x7c, 0x5b, 0x23,
	0x69, 0x16, 0x81, 0xbf, 0x90, 0x39, 0x96, 0xa2, 0xc0, 0xb0, 0x37, 0xee, 0x4d, 0x8e, 0x92, 0xef,
	0x9a, 0xcf, 0xe0, 0xd8, 0xb6, 0xd3, 0x4a, 0x95, 0x84, 0x2c, 0x84, 0xc3, 0x0d, 0x56, 0x24, 0x55,
	0xd9, 0xb4, 0x0f, 0x12, 0x53, 0xd6, 0xa4, 0xa5, 0xa0, 0xe5, 0x83, 0x24, 0x1d, 0x7a, 0xe3, 0x7e,
	0x4d, 0x32, 0x35, 0x47, 0x08, 0xe6, 0x2a, 0x93, 0x8b, 0xf7, 0x3d, 0xa5, 0xdb, 0x32, 0xde, 0xdf,
	0x32, 0xfd, 0x8e, 0xcc, 0x33, 0xb0, 0xb6, 0x8c, 0x1d, 0x99, 0xd6, 0x69, 0x8a, 0x44, 0x8d, 0x8c,
	0x9f, 0x98, 0x92, 0x4d, 0x60, 0x54, 0x48, 0x22, 0x59, 0xbe, 0xce, 0x7e, 0x4e, 0xde, 0x3d, 0xe6,
	0xf7, 0x10, 0xdc, 0x60, 0x8e, 0x1a, 0xff, 0xfd, 0x00, 0x1e, 0x03, 0x6b, 0xa3, 0x76, 0x0d, 0xc9,
	0x2f, 0x20, 0xb8, 0x43, 0xfd, 0xb4, 0xbd, 0xbd, 0x4f, 0x6c, 0x31, 0xb0, 0xf6, 0x85, 0x5d, 0xc1,
	0x5d, 0x7e, 0x78, 0x30, 0x9c, 0xa3, 0x16, 0x99, 0xd0, 0xe2, 0x51, 0xab, 0x0a, 0xd9, 0x35, 0xf8,
	0x26, 0x78, 0x76, 0x12, 0xd7, 0xab, 0x13, 0x77, 0xf6, 0x26, 0x3a, 0xed, 0x1e, 0x7f, 0xc9, 0x4c,
	0x01, 0x6c, 0x04, 0xec, 0x6c, 0xdb, 0xe5, 0x64, 0x1f, 0x85, 0xee, 0x07, 0x0b, 0xb0, 0xf6, 0x18,
	0x80, 0xe3, 0xbd, 0x01, 0xfc, 0xe2, 0xe4, 0x14, 0xc0, 0x3e, 0xdf, 0x00, 0x1c, 0x07, 0x0d, 0xc0,
	0x75, 0xea, 0xe5, 0xa0, 0xf9, 0x65, 0xae, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x59, 0x78,
	0x6d, 0x43, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetadataStoreClient is the client API for MetadataStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataStoreClient interface {
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	ModifyFile(ctx context.Context, in *ModifyFileRequest, opts ...grpc.CallOption) (*ModifyFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
}

type metadataStoreClient struct {
	cc *grpc.ClientConn
}

func NewMetadataStoreClient(cc *grpc.ClientConn) MetadataStoreClient {
	return &metadataStoreClient{cc}
}

func (c *metadataStoreClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, "/meta.MetadataStore/ReadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataStoreClient) ModifyFile(ctx context.Context, in *ModifyFileRequest, opts ...grpc.CallOption) (*ModifyFileResponse, error) {
	out := new(ModifyFileResponse)
	err := c.cc.Invoke(ctx, "/meta.MetadataStore/ModifyFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataStoreClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/meta.MetadataStore/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataStoreClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, "/meta.MetadataStore/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataStoreServer is the server API for MetadataStore service.
type MetadataStoreServer interface {
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	ModifyFile(context.Context, *ModifyFileRequest) (*ModifyFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
}

// UnimplementedMetadataStoreServer can be embedded to have forward compatible implementations.
type UnimplementedMetadataStoreServer struct {
}

func (*UnimplementedMetadataStoreServer) ReadFile(ctx context.Context, req *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (*UnimplementedMetadataStoreServer) ModifyFile(ctx context.Context, req *ModifyFileRequest) (*ModifyFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyFile not implemented")
}
func (*UnimplementedMetadataStoreServer) DeleteFile(ctx context.Context, req *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (*UnimplementedMetadataStoreServer) GetVersion(ctx context.Context, req *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

func RegisterMetadataStoreServer(s *grpc.Server, srv MetadataStoreServer) {
	s.RegisterService(&_MetadataStore_serviceDesc, srv)
}

func _MetadataStore_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataStoreServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.MetadataStore/ReadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataStoreServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataStore_ModifyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataStoreServer).ModifyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.MetadataStore/ModifyFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataStoreServer).ModifyFile(ctx, req.(*ModifyFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataStore_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataStoreServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.MetadataStore/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataStoreServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataStore_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataStoreServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.MetadataStore/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataStoreServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetadataStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meta.MetadataStore",
	HandlerType: (*MetadataStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadFile",
			Handler:    _MetadataStore_ReadFile_Handler,
		},
		{
			MethodName: "ModifyFile",
			Handler:    _MetadataStore_ModifyFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _MetadataStore_DeleteFile_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _MetadataStore_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
